name: travel_on_final
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  table_calendar: ^3.1.2

  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1

  # 권한
  permission_handler: ^11.3.1

  #firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2

  #소셜 로그인
  kakao_flutter_sdk: ^1.9.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.6

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/travel-on-login.png
    - assets/images/default_profile.png
    - assets/images/logo/google.png
    - assets/images/logo/naver.png
    - assets/images/logo/facebook.png
    - assets/images/logo/kakaotalk.png
    - .env
